language: csharp
solution: travis-test.sln
mono: weekly
script:
  - xbuild /p:Configuration=Release travis-test.sln
  - mono ./packages/xunit.runner.console.*/tools/xunit.console.x86.exe ./travis-test/bin/Release/travis-test.dll
